// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amazon_ups.proto

#ifndef PROTOBUF_INCLUDED_amazon_5fups_2eproto
#define PROTOBUF_INCLUDED_amazon_5fups_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_amazon_5fups_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_amazon_5fups_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_amazon_5fups_2eproto();
class AUCommands;
class AUCommandsDefaultTypeInternal;
extern AUCommandsDefaultTypeInternal _AUCommands_default_instance_;
class AWarehouse;
class AWarehouseDefaultTypeInternal;
extern AWarehouseDefaultTypeInternal _AWarehouse_default_instance_;
class Deliver;
class DeliverDefaultTypeInternal;
extern DeliverDefaultTypeInternal _Deliver_default_instance_;
class Delivered;
class DeliveredDefaultTypeInternal;
extern DeliveredDefaultTypeInternal _Delivered_default_instance_;
class Order;
class OrderDefaultTypeInternal;
extern OrderDefaultTypeInternal _Order_default_instance_;
class Product;
class ProductDefaultTypeInternal;
extern ProductDefaultTypeInternal _Product_default_instance_;
class Truck;
class TruckDefaultTypeInternal;
extern TruckDefaultTypeInternal _Truck_default_instance_;
class UACommands;
class UACommandsDefaultTypeInternal;
extern UACommandsDefaultTypeInternal _UACommands_default_instance_;
namespace google {
namespace protobuf {
template<> ::AUCommands* Arena::CreateMaybeMessage<::AUCommands>(Arena*);
template<> ::AWarehouse* Arena::CreateMaybeMessage<::AWarehouse>(Arena*);
template<> ::Deliver* Arena::CreateMaybeMessage<::Deliver>(Arena*);
template<> ::Delivered* Arena::CreateMaybeMessage<::Delivered>(Arena*);
template<> ::Order* Arena::CreateMaybeMessage<::Order>(Arena*);
template<> ::Product* Arena::CreateMaybeMessage<::Product>(Arena*);
template<> ::Truck* Arena::CreateMaybeMessage<::Truck>(Arena*);
template<> ::UACommands* Arena::CreateMaybeMessage<::UACommands>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class Product :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Product) */ {
 public:
  Product();
  virtual ~Product();

  Product(const Product& from);

  inline Product& operator=(const Product& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Product(Product&& from) noexcept
    : Product() {
    *this = ::std::move(from);
  }

  inline Product& operator=(Product&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Product& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Product* internal_default_instance() {
    return reinterpret_cast<const Product*>(
               &_Product_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Product* other);
  friend void swap(Product& a, Product& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Product* New() const final {
    return CreateMaybeMessage<Product>(nullptr);
  }

  Product* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Product>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Product& from);
  void MergeFrom(const Product& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Product* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string description = 2;
  bool has_description() const;
  void clear_description();
  static const int kDescriptionFieldNumber = 2;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // required int32 amount = 3;
  bool has_amount() const;
  void clear_amount();
  static const int kAmountFieldNumber = 3;
  ::google::protobuf::int32 amount() const;
  void set_amount(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Product)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 amount_;
  friend struct ::TableStruct_amazon_5fups_2eproto;
};
// -------------------------------------------------------------------

class Order :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Order) */ {
 public:
  Order();
  virtual ~Order();

  Order(const Order& from);

  inline Order& operator=(const Order& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Order(Order&& from) noexcept
    : Order() {
    *this = ::std::move(from);
  }

  inline Order& operator=(Order&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Order& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Order* internal_default_instance() {
    return reinterpret_cast<const Order*>(
               &_Order_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Order* other);
  friend void swap(Order& a, Order& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Order* New() const final {
    return CreateMaybeMessage<Order>(nullptr);
  }

  Order* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Order>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Order& from);
  void MergeFrom(const Order& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Order* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Product item = 6;
  int item_size() const;
  void clear_item();
  static const int kItemFieldNumber = 6;
  ::Product* mutable_item(int index);
  ::google::protobuf::RepeatedPtrField< ::Product >*
      mutable_item();
  const ::Product& item(int index) const;
  ::Product* add_item();
  const ::google::protobuf::RepeatedPtrField< ::Product >&
      item() const;

  // required string upsusername = 5;
  bool has_upsusername() const;
  void clear_upsusername();
  static const int kUpsusernameFieldNumber = 5;
  const ::std::string& upsusername() const;
  void set_upsusername(const ::std::string& value);
  #if LANG_CXX11
  void set_upsusername(::std::string&& value);
  #endif
  void set_upsusername(const char* value);
  void set_upsusername(const char* value, size_t size);
  ::std::string* mutable_upsusername();
  ::std::string* release_upsusername();
  void set_allocated_upsusername(::std::string* upsusername);

  // required int32 whid = 1;
  bool has_whid() const;
  void clear_whid();
  static const int kWhidFieldNumber = 1;
  ::google::protobuf::int32 whid() const;
  void set_whid(::google::protobuf::int32 value);

  // required int32 x = 2;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 2;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int64 packageid = 4;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 4;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int64 seqnum = 7;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 7;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // required int32 y = 3;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 3;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Order)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Product > item_;
  ::google::protobuf::internal::ArenaStringPtr upsusername_;
  ::google::protobuf::int32 whid_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int64 seqnum_;
  ::google::protobuf::int32 y_;
  friend struct ::TableStruct_amazon_5fups_2eproto;
};
// -------------------------------------------------------------------

class Deliver :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Deliver) */ {
 public:
  Deliver();
  virtual ~Deliver();

  Deliver(const Deliver& from);

  inline Deliver& operator=(const Deliver& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Deliver(Deliver&& from) noexcept
    : Deliver() {
    *this = ::std::move(from);
  }

  inline Deliver& operator=(Deliver&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Deliver& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Deliver* internal_default_instance() {
    return reinterpret_cast<const Deliver*>(
               &_Deliver_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Deliver* other);
  friend void swap(Deliver& a, Deliver& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Deliver* New() const final {
    return CreateMaybeMessage<Deliver>(nullptr);
  }

  Deliver* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Deliver>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Deliver& from);
  void MergeFrom(const Deliver& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Deliver* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 packageid = 1;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 1;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Deliver)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_amazon_5fups_2eproto;
};
// -------------------------------------------------------------------

class AWarehouse :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AWarehouse) */ {
 public:
  AWarehouse();
  virtual ~AWarehouse();

  AWarehouse(const AWarehouse& from);

  inline AWarehouse& operator=(const AWarehouse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AWarehouse(AWarehouse&& from) noexcept
    : AWarehouse() {
    *this = ::std::move(from);
  }

  inline AWarehouse& operator=(AWarehouse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const AWarehouse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AWarehouse* internal_default_instance() {
    return reinterpret_cast<const AWarehouse*>(
               &_AWarehouse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(AWarehouse* other);
  friend void swap(AWarehouse& a, AWarehouse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AWarehouse* New() const final {
    return CreateMaybeMessage<AWarehouse>(nullptr);
  }

  AWarehouse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AWarehouse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AWarehouse& from);
  void MergeFrom(const AWarehouse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AWarehouse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // required int32 x = 2;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 2;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int64 seqnum = 4;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 4;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // required int32 y = 3;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 3;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:AWarehouse)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int64 seqnum_;
  ::google::protobuf::int32 y_;
  friend struct ::TableStruct_amazon_5fups_2eproto;
};
// -------------------------------------------------------------------

class AUCommands :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AUCommands) */ {
 public:
  AUCommands();
  virtual ~AUCommands();

  AUCommands(const AUCommands& from);

  inline AUCommands& operator=(const AUCommands& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AUCommands(AUCommands&& from) noexcept
    : AUCommands() {
    *this = ::std::move(from);
  }

  inline AUCommands& operator=(AUCommands&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const AUCommands& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AUCommands* internal_default_instance() {
    return reinterpret_cast<const AUCommands*>(
               &_AUCommands_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(AUCommands* other);
  friend void swap(AUCommands& a, AUCommands& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AUCommands* New() const final {
    return CreateMaybeMessage<AUCommands>(nullptr);
  }

  AUCommands* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AUCommands>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AUCommands& from);
  void MergeFrom(const AUCommands& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AUCommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Order order = 1;
  int order_size() const;
  void clear_order();
  static const int kOrderFieldNumber = 1;
  ::Order* mutable_order(int index);
  ::google::protobuf::RepeatedPtrField< ::Order >*
      mutable_order();
  const ::Order& order(int index) const;
  ::Order* add_order();
  const ::google::protobuf::RepeatedPtrField< ::Order >&
      order() const;

  // repeated .Deliver todeliver = 2;
  int todeliver_size() const;
  void clear_todeliver();
  static const int kTodeliverFieldNumber = 2;
  ::Deliver* mutable_todeliver(int index);
  ::google::protobuf::RepeatedPtrField< ::Deliver >*
      mutable_todeliver();
  const ::Deliver& todeliver(int index) const;
  ::Deliver* add_todeliver();
  const ::google::protobuf::RepeatedPtrField< ::Deliver >&
      todeliver() const;

  // repeated .AWarehouse whinfo = 3;
  int whinfo_size() const;
  void clear_whinfo();
  static const int kWhinfoFieldNumber = 3;
  ::AWarehouse* mutable_whinfo(int index);
  ::google::protobuf::RepeatedPtrField< ::AWarehouse >*
      mutable_whinfo();
  const ::AWarehouse& whinfo(int index) const;
  ::AWarehouse* add_whinfo();
  const ::google::protobuf::RepeatedPtrField< ::AWarehouse >&
      whinfo() const;

  // repeated int64 acks = 4;
  int acks_size() const;
  void clear_acks();
  static const int kAcksFieldNumber = 4;
  ::google::protobuf::int64 acks(int index) const;
  void set_acks(int index, ::google::protobuf::int64 value);
  void add_acks(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      acks() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_acks();

  // @@protoc_insertion_point(class_scope:AUCommands)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Order > order_;
  ::google::protobuf::RepeatedPtrField< ::Deliver > todeliver_;
  ::google::protobuf::RepeatedPtrField< ::AWarehouse > whinfo_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > acks_;
  friend struct ::TableStruct_amazon_5fups_2eproto;
};
// -------------------------------------------------------------------

class Truck :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Truck) */ {
 public:
  Truck();
  virtual ~Truck();

  Truck(const Truck& from);

  inline Truck& operator=(const Truck& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Truck(Truck&& from) noexcept
    : Truck() {
    *this = ::std::move(from);
  }

  inline Truck& operator=(Truck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Truck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Truck* internal_default_instance() {
    return reinterpret_cast<const Truck*>(
               &_Truck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Truck* other);
  friend void swap(Truck& a, Truck& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Truck* New() const final {
    return CreateMaybeMessage<Truck>(nullptr);
  }

  Truck* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Truck>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Truck& from);
  void MergeFrom(const Truck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Truck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 whid = 1;
  bool has_whid() const;
  void clear_whid();
  static const int kWhidFieldNumber = 1;
  ::google::protobuf::int32 whid() const;
  void set_whid(::google::protobuf::int32 value);

  // required int32 truckid = 2;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 2;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // required int64 packageid = 3;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 3;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int64 seqnum = 4;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 4;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Truck)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 whid_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_amazon_5fups_2eproto;
};
// -------------------------------------------------------------------

class Delivered :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Delivered) */ {
 public:
  Delivered();
  virtual ~Delivered();

  Delivered(const Delivered& from);

  inline Delivered& operator=(const Delivered& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Delivered(Delivered&& from) noexcept
    : Delivered() {
    *this = ::std::move(from);
  }

  inline Delivered& operator=(Delivered&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Delivered& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Delivered* internal_default_instance() {
    return reinterpret_cast<const Delivered*>(
               &_Delivered_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(Delivered* other);
  friend void swap(Delivered& a, Delivered& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Delivered* New() const final {
    return CreateMaybeMessage<Delivered>(nullptr);
  }

  Delivered* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Delivered>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Delivered& from);
  void MergeFrom(const Delivered& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Delivered* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 packageid = 1;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 1;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Delivered)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_amazon_5fups_2eproto;
};
// -------------------------------------------------------------------

class UACommands :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UACommands) */ {
 public:
  UACommands();
  virtual ~UACommands();

  UACommands(const UACommands& from);

  inline UACommands& operator=(const UACommands& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UACommands(UACommands&& from) noexcept
    : UACommands() {
    *this = ::std::move(from);
  }

  inline UACommands& operator=(UACommands&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const UACommands& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UACommands* internal_default_instance() {
    return reinterpret_cast<const UACommands*>(
               &_UACommands_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(UACommands* other);
  friend void swap(UACommands& a, UACommands& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UACommands* New() const final {
    return CreateMaybeMessage<UACommands>(nullptr);
  }

  UACommands* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UACommands>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UACommands& from);
  void MergeFrom(const UACommands& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UACommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Truck arrived = 1;
  int arrived_size() const;
  void clear_arrived();
  static const int kArrivedFieldNumber = 1;
  ::Truck* mutable_arrived(int index);
  ::google::protobuf::RepeatedPtrField< ::Truck >*
      mutable_arrived();
  const ::Truck& arrived(int index) const;
  ::Truck* add_arrived();
  const ::google::protobuf::RepeatedPtrField< ::Truck >&
      arrived() const;

  // repeated .Delivered finish = 2;
  int finish_size() const;
  void clear_finish();
  static const int kFinishFieldNumber = 2;
  ::Delivered* mutable_finish(int index);
  ::google::protobuf::RepeatedPtrField< ::Delivered >*
      mutable_finish();
  const ::Delivered& finish(int index) const;
  ::Delivered* add_finish();
  const ::google::protobuf::RepeatedPtrField< ::Delivered >&
      finish() const;

  // repeated int64 acks = 3;
  int acks_size() const;
  void clear_acks();
  static const int kAcksFieldNumber = 3;
  ::google::protobuf::int64 acks(int index) const;
  void set_acks(int index, ::google::protobuf::int64 value);
  void add_acks(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      acks() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_acks();

  // @@protoc_insertion_point(class_scope:UACommands)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Truck > arrived_;
  ::google::protobuf::RepeatedPtrField< ::Delivered > finish_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > acks_;
  friend struct ::TableStruct_amazon_5fups_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Product

// required int32 id = 1;
inline bool Product::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Product::clear_id() {
  id_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 Product::id() const {
  // @@protoc_insertion_point(field_get:Product.id)
  return id_;
}
inline void Product::set_id(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  id_ = value;
  // @@protoc_insertion_point(field_set:Product.id)
}

// required string description = 2;
inline bool Product::has_description() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Product::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& Product::description() const {
  // @@protoc_insertion_point(field_get:Product.description)
  return description_.GetNoArena();
}
inline void Product::set_description(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Product.description)
}
#if LANG_CXX11
inline void Product::set_description(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Product.description)
}
#endif
inline void Product::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Product.description)
}
inline void Product::set_description(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Product.description)
}
inline ::std::string* Product::mutable_description() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:Product.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Product::release_description() {
  // @@protoc_insertion_point(field_release:Product.description)
  if (!has_description()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return description_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Product::set_allocated_description(::std::string* description) {
  if (description != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:Product.description)
}

// required int32 amount = 3;
inline bool Product::has_amount() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Product::clear_amount() {
  amount_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int32 Product::amount() const {
  // @@protoc_insertion_point(field_get:Product.amount)
  return amount_;
}
inline void Product::set_amount(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  amount_ = value;
  // @@protoc_insertion_point(field_set:Product.amount)
}

// -------------------------------------------------------------------

// Order

// required int32 whid = 1;
inline bool Order::has_whid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Order::clear_whid() {
  whid_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 Order::whid() const {
  // @@protoc_insertion_point(field_get:Order.whid)
  return whid_;
}
inline void Order::set_whid(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  whid_ = value;
  // @@protoc_insertion_point(field_set:Order.whid)
}

// required int32 x = 2;
inline bool Order::has_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Order::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int32 Order::x() const {
  // @@protoc_insertion_point(field_get:Order.x)
  return x_;
}
inline void Order::set_x(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  x_ = value;
  // @@protoc_insertion_point(field_set:Order.x)
}

// required int32 y = 3;
inline bool Order::has_y() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Order::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::google::protobuf::int32 Order::y() const {
  // @@protoc_insertion_point(field_get:Order.y)
  return y_;
}
inline void Order::set_y(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000020u;
  y_ = value;
  // @@protoc_insertion_point(field_set:Order.y)
}

// required int64 packageid = 4;
inline bool Order::has_packageid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Order::clear_packageid() {
  packageid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int64 Order::packageid() const {
  // @@protoc_insertion_point(field_get:Order.packageid)
  return packageid_;
}
inline void Order::set_packageid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000008u;
  packageid_ = value;
  // @@protoc_insertion_point(field_set:Order.packageid)
}

// required string upsusername = 5;
inline bool Order::has_upsusername() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Order::clear_upsusername() {
  upsusername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& Order::upsusername() const {
  // @@protoc_insertion_point(field_get:Order.upsusername)
  return upsusername_.GetNoArena();
}
inline void Order::set_upsusername(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  upsusername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Order.upsusername)
}
#if LANG_CXX11
inline void Order::set_upsusername(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  upsusername_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Order.upsusername)
}
#endif
inline void Order::set_upsusername(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  upsusername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Order.upsusername)
}
inline void Order::set_upsusername(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  upsusername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Order.upsusername)
}
inline ::std::string* Order::mutable_upsusername() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:Order.upsusername)
  return upsusername_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Order::release_upsusername() {
  // @@protoc_insertion_point(field_release:Order.upsusername)
  if (!has_upsusername()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return upsusername_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Order::set_allocated_upsusername(::std::string* upsusername) {
  if (upsusername != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  upsusername_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), upsusername);
  // @@protoc_insertion_point(field_set_allocated:Order.upsusername)
}

// repeated .Product item = 6;
inline int Order::item_size() const {
  return item_.size();
}
inline void Order::clear_item() {
  item_.Clear();
}
inline ::Product* Order::mutable_item(int index) {
  // @@protoc_insertion_point(field_mutable:Order.item)
  return item_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Product >*
Order::mutable_item() {
  // @@protoc_insertion_point(field_mutable_list:Order.item)
  return &item_;
}
inline const ::Product& Order::item(int index) const {
  // @@protoc_insertion_point(field_get:Order.item)
  return item_.Get(index);
}
inline ::Product* Order::add_item() {
  // @@protoc_insertion_point(field_add:Order.item)
  return item_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Product >&
Order::item() const {
  // @@protoc_insertion_point(field_list:Order.item)
  return item_;
}

// required int64 seqnum = 7;
inline bool Order::has_seqnum() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Order::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::int64 Order::seqnum() const {
  // @@protoc_insertion_point(field_get:Order.seqnum)
  return seqnum_;
}
inline void Order::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000010u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:Order.seqnum)
}

// -------------------------------------------------------------------

// Deliver

// required int64 packageid = 1;
inline bool Deliver::has_packageid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Deliver::clear_packageid() {
  packageid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 Deliver::packageid() const {
  // @@protoc_insertion_point(field_get:Deliver.packageid)
  return packageid_;
}
inline void Deliver::set_packageid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  packageid_ = value;
  // @@protoc_insertion_point(field_set:Deliver.packageid)
}

// required int64 seqnum = 2;
inline bool Deliver::has_seqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Deliver::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int64 Deliver::seqnum() const {
  // @@protoc_insertion_point(field_get:Deliver.seqnum)
  return seqnum_;
}
inline void Deliver::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:Deliver.seqnum)
}

// -------------------------------------------------------------------

// AWarehouse

// required int32 id = 1;
inline bool AWarehouse::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AWarehouse::clear_id() {
  id_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int32 AWarehouse::id() const {
  // @@protoc_insertion_point(field_get:AWarehouse.id)
  return id_;
}
inline void AWarehouse::set_id(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  id_ = value;
  // @@protoc_insertion_point(field_set:AWarehouse.id)
}

// required int32 x = 2;
inline bool AWarehouse::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AWarehouse::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 AWarehouse::x() const {
  // @@protoc_insertion_point(field_get:AWarehouse.x)
  return x_;
}
inline void AWarehouse::set_x(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  x_ = value;
  // @@protoc_insertion_point(field_set:AWarehouse.x)
}

// required int32 y = 3;
inline bool AWarehouse::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AWarehouse::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 AWarehouse::y() const {
  // @@protoc_insertion_point(field_get:AWarehouse.y)
  return y_;
}
inline void AWarehouse::set_y(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  y_ = value;
  // @@protoc_insertion_point(field_set:AWarehouse.y)
}

// required int64 seqnum = 4;
inline bool AWarehouse::has_seqnum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AWarehouse::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int64 AWarehouse::seqnum() const {
  // @@protoc_insertion_point(field_get:AWarehouse.seqnum)
  return seqnum_;
}
inline void AWarehouse::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:AWarehouse.seqnum)
}

// -------------------------------------------------------------------

// AUCommands

// repeated .Order order = 1;
inline int AUCommands::order_size() const {
  return order_.size();
}
inline void AUCommands::clear_order() {
  order_.Clear();
}
inline ::Order* AUCommands::mutable_order(int index) {
  // @@protoc_insertion_point(field_mutable:AUCommands.order)
  return order_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Order >*
AUCommands::mutable_order() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.order)
  return &order_;
}
inline const ::Order& AUCommands::order(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.order)
  return order_.Get(index);
}
inline ::Order* AUCommands::add_order() {
  // @@protoc_insertion_point(field_add:AUCommands.order)
  return order_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Order >&
AUCommands::order() const {
  // @@protoc_insertion_point(field_list:AUCommands.order)
  return order_;
}

// repeated .Deliver todeliver = 2;
inline int AUCommands::todeliver_size() const {
  return todeliver_.size();
}
inline void AUCommands::clear_todeliver() {
  todeliver_.Clear();
}
inline ::Deliver* AUCommands::mutable_todeliver(int index) {
  // @@protoc_insertion_point(field_mutable:AUCommands.todeliver)
  return todeliver_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Deliver >*
AUCommands::mutable_todeliver() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.todeliver)
  return &todeliver_;
}
inline const ::Deliver& AUCommands::todeliver(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.todeliver)
  return todeliver_.Get(index);
}
inline ::Deliver* AUCommands::add_todeliver() {
  // @@protoc_insertion_point(field_add:AUCommands.todeliver)
  return todeliver_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Deliver >&
AUCommands::todeliver() const {
  // @@protoc_insertion_point(field_list:AUCommands.todeliver)
  return todeliver_;
}

// repeated .AWarehouse whinfo = 3;
inline int AUCommands::whinfo_size() const {
  return whinfo_.size();
}
inline void AUCommands::clear_whinfo() {
  whinfo_.Clear();
}
inline ::AWarehouse* AUCommands::mutable_whinfo(int index) {
  // @@protoc_insertion_point(field_mutable:AUCommands.whinfo)
  return whinfo_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::AWarehouse >*
AUCommands::mutable_whinfo() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.whinfo)
  return &whinfo_;
}
inline const ::AWarehouse& AUCommands::whinfo(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.whinfo)
  return whinfo_.Get(index);
}
inline ::AWarehouse* AUCommands::add_whinfo() {
  // @@protoc_insertion_point(field_add:AUCommands.whinfo)
  return whinfo_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::AWarehouse >&
AUCommands::whinfo() const {
  // @@protoc_insertion_point(field_list:AUCommands.whinfo)
  return whinfo_;
}

// repeated int64 acks = 4;
inline int AUCommands::acks_size() const {
  return acks_.size();
}
inline void AUCommands::clear_acks() {
  acks_.Clear();
}
inline ::google::protobuf::int64 AUCommands::acks(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.acks)
  return acks_.Get(index);
}
inline void AUCommands::set_acks(int index, ::google::protobuf::int64 value) {
  acks_.Set(index, value);
  // @@protoc_insertion_point(field_set:AUCommands.acks)
}
inline void AUCommands::add_acks(::google::protobuf::int64 value) {
  acks_.Add(value);
  // @@protoc_insertion_point(field_add:AUCommands.acks)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
AUCommands::acks() const {
  // @@protoc_insertion_point(field_list:AUCommands.acks)
  return acks_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
AUCommands::mutable_acks() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.acks)
  return &acks_;
}

// -------------------------------------------------------------------

// Truck

// required int32 whid = 1;
inline bool Truck::has_whid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Truck::clear_whid() {
  whid_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int32 Truck::whid() const {
  // @@protoc_insertion_point(field_get:Truck.whid)
  return whid_;
}
inline void Truck::set_whid(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  whid_ = value;
  // @@protoc_insertion_point(field_set:Truck.whid)
}

// required int32 truckid = 2;
inline bool Truck::has_truckid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Truck::clear_truckid() {
  truckid_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 Truck::truckid() const {
  // @@protoc_insertion_point(field_get:Truck.truckid)
  return truckid_;
}
inline void Truck::set_truckid(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  truckid_ = value;
  // @@protoc_insertion_point(field_set:Truck.truckid)
}

// required int64 packageid = 3;
inline bool Truck::has_packageid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Truck::clear_packageid() {
  packageid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int64 Truck::packageid() const {
  // @@protoc_insertion_point(field_get:Truck.packageid)
  return packageid_;
}
inline void Truck::set_packageid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  packageid_ = value;
  // @@protoc_insertion_point(field_set:Truck.packageid)
}

// required int64 seqnum = 4;
inline bool Truck::has_seqnum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Truck::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int64 Truck::seqnum() const {
  // @@protoc_insertion_point(field_get:Truck.seqnum)
  return seqnum_;
}
inline void Truck::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000008u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:Truck.seqnum)
}

// -------------------------------------------------------------------

// Delivered

// required int64 packageid = 1;
inline bool Delivered::has_packageid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Delivered::clear_packageid() {
  packageid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 Delivered::packageid() const {
  // @@protoc_insertion_point(field_get:Delivered.packageid)
  return packageid_;
}
inline void Delivered::set_packageid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  packageid_ = value;
  // @@protoc_insertion_point(field_set:Delivered.packageid)
}

// required int64 seqnum = 2;
inline bool Delivered::has_seqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Delivered::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int64 Delivered::seqnum() const {
  // @@protoc_insertion_point(field_get:Delivered.seqnum)
  return seqnum_;
}
inline void Delivered::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:Delivered.seqnum)
}

// -------------------------------------------------------------------

// UACommands

// repeated .Truck arrived = 1;
inline int UACommands::arrived_size() const {
  return arrived_.size();
}
inline void UACommands::clear_arrived() {
  arrived_.Clear();
}
inline ::Truck* UACommands::mutable_arrived(int index) {
  // @@protoc_insertion_point(field_mutable:UACommands.arrived)
  return arrived_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Truck >*
UACommands::mutable_arrived() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.arrived)
  return &arrived_;
}
inline const ::Truck& UACommands::arrived(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.arrived)
  return arrived_.Get(index);
}
inline ::Truck* UACommands::add_arrived() {
  // @@protoc_insertion_point(field_add:UACommands.arrived)
  return arrived_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Truck >&
UACommands::arrived() const {
  // @@protoc_insertion_point(field_list:UACommands.arrived)
  return arrived_;
}

// repeated .Delivered finish = 2;
inline int UACommands::finish_size() const {
  return finish_.size();
}
inline void UACommands::clear_finish() {
  finish_.Clear();
}
inline ::Delivered* UACommands::mutable_finish(int index) {
  // @@protoc_insertion_point(field_mutable:UACommands.finish)
  return finish_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::Delivered >*
UACommands::mutable_finish() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.finish)
  return &finish_;
}
inline const ::Delivered& UACommands::finish(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.finish)
  return finish_.Get(index);
}
inline ::Delivered* UACommands::add_finish() {
  // @@protoc_insertion_point(field_add:UACommands.finish)
  return finish_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Delivered >&
UACommands::finish() const {
  // @@protoc_insertion_point(field_list:UACommands.finish)
  return finish_;
}

// repeated int64 acks = 3;
inline int UACommands::acks_size() const {
  return acks_.size();
}
inline void UACommands::clear_acks() {
  acks_.Clear();
}
inline ::google::protobuf::int64 UACommands::acks(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.acks)
  return acks_.Get(index);
}
inline void UACommands::set_acks(int index, ::google::protobuf::int64 value) {
  acks_.Set(index, value);
  // @@protoc_insertion_point(field_set:UACommands.acks)
}
inline void UACommands::add_acks(::google::protobuf::int64 value) {
  acks_.Add(value);
  // @@protoc_insertion_point(field_add:UACommands.acks)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
UACommands::acks() const {
  // @@protoc_insertion_point(field_list:UACommands.acks)
  return acks_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
UACommands::mutable_acks() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.acks)
  return &acks_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_amazon_5fups_2eproto
