# Generated by Django 2.2 on 2019-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.CharField(max_length=1000)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
    ]
