# Generated by Django 2.2 on 2019-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('tracking_number', models.AutoField(primary_key=True, serialize=False)),
                ('credit_card', models.CharField(max_length=16)),
                ('user_id', models.IntegerField()),
                ('product_name', models.TextField()),
                ('amount', models.IntegerField(default=1)),
                ('address_x', models.TextField()),
                ('address_y', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.TextField()),
                ('wh_id', models.IntegerField()),
                ('stock', models.IntegerField(default=500)),
            ],
            options={
                'unique_together': {('product_id', 'wh_id')},
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
