# Generated by Django 2.2 on 2019-04-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190418_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='address_x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='address_y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
    ]
