# Generated by Django 2.2 on 2019-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190418_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='ups_account',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
