# Generated by Django 2.2 on 2019-04-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_pendingorder_ups_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='ups_account',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
