# Generated by Django 2.2 on 2019-04-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190419_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('tracking_number', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('ups_account', models.CharField(max_length=500)),
                ('product_id', models.IntegerField()),
                ('wh_id', models.IntegerField()),
                ('truck_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('adr_x', models.IntegerField()),
                ('adr_y', models.IntegerField()),
            ],
        ),
    ]
