# Generated by Django 2.2 on 2019-04-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
