# Generated by Django 2.2 on 2019-04-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_cart_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
    ]
